#!/bin/bash

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "Docker is not installed or not in PATH. Please install Docker."
    exit 1
fi

# Check if the container exists
if ! docker ps -a --format '{{.Names}}' | grep -q '^cka-worker2$'; then
    echo "The container 'cka-control-plane' does not exist."
    exit 1
fi

# Open an interactive terminal inside the container
docker exec -it cka-worker2 bash
